### ISSUE TITLE
Multiple modals and their background

### ISSUE THREAD

**Issue by matejp84** [appiphony/appiphony-lightning-js#2]
Hi,

I have just started using this library and so far so good, but I have some visual problems with modals. 

On my page I'm using multiple modals (sometimes I even switch from one modal to other). For example: customer is able to add a row into table which represents one objects that holds data about vendor, product and so on. To add new line user is presented with first modal. There they can search for existing vendors in database and they can also make new one which opens another dialog. 
Problem here now is that background works perfectly on first modal, but when second opens it disappears and it doesn't show back up even when switching from second modal to first one. 
Maybe I'm only using this library wrong and this is not bug, but I would like to fix it to give our customers good UX with animated modals and lots of feedback. I also have modal for saving action (VFRemoting, modal is visible until I get response feedback from controller). 

import statements are:
`<apex:includeScript value="{!URLFOR($Resource.aljs, '/jquery/jquery.aljs-init.min.js')}"/>
        <apex:includeScript value="{!URLFOR($Resource.aljs, '/jquery/jquery.aljs-modal.min.js')}"/>`
javacript init is:
`
$.aljsInit({
            scoped: true
        });

        $(document).ready(function() {
            $('[data-aljs="modal"]').modal();
        });`

and then in html I added data-aljs-dismiss="modal" on things that closes modal and I'm showing it with: data-aljs="modal" data-aljs-show="savingDialog"
If I wish to programmatically open modal I use:
$('#savingDialog').modal('dismiss'); and $('#savingDialog').modal('show');

Am I doing anything wrong here?

**Comment by djlimbs** [comment]
Hi,

Thanks for trying our library out! I'd just like to clarify that you are running code to dismiss one modal, then show another. Such as:

function a() {
   $('#modal-1').modal('dismiss');
   $('#modal-2').modal('show');
}

Is that correct?

If so, then this is a bug with our plugin where programmatically showing/dismissing modals in succession is not happening synchronously. We will log this and update you with a fix very soon.

Cheers!

Victor

**Comment by matejp84** [comment]
Hi,

I have tried both ways:
`
$('#dialog-1').modal('dismiss');
            $('#dialog-2').modal('show');
//and this one:
            $('[data-aljs-show="dialog-2"]').modal('trigger');
`
I suspect that problem is somewhere with removing some CSS class and it is not attached back to the new dialog. I have multiple pages where I use "nested modals", one is opened from another or there is saving or loading modal in between to show user status of operation. 
Do you have any approximate ETA when this might get fixed so I can forward it to my customer when they can expect those fixes?

**Comment by djlimbs** [comment]
I matej, we have implemented a fix for this and will release a new version Friday (Nov 13).

**Comment by matejp84** [comment]
Hi,

I updated aljs but background on dialogs still doesn't work correctly if I close first one and open second one.

**Comment by djlimbs** [comment]
Hi, we have tested using  $('#dialog-1').modal('dismiss'); $('#dialog-2').modal('show'); and it works in our code examples. Can you provide more information about your use case? Specifically about how you are launching your "nested modals". Are you running the show/dismiss code in the callback functions?

**Comment by matejp84** [comment]
Hi,

looks like I made a big mistake and forgot to properly save my project file to refence new aljs package I have uploaded into static resources. Sorry for that, it works now perfectly. Thank you for fix :)
